import type { Metadata } from "next";
import "./globals.css";
import MenuVertical from "../../componentes/MenuVertical";

export const metadata: Metadata = {
  title: "DELL Transportes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="font-sans overflow-hidden flex flex-col p-2 bg-branco h-svh">
          <div className="bg-verdeMedioClaro w-[100%] rounded-md p-2 text-center mx-auto flex flex-row items-center justify-between">
            <div className="w-1/4 text-left">
              <h1 className="text-2xl text-white font-semibold">DELL Transportes</h1>
            </div>
            <MenuVertical />
          </div>

          <div className="mt-1 bg-verdeMedioClaro w-full rounded-md p-2 flex-grow h-[500px]">
            {children}
          </div>
      </div>
      </body>
    </html>
  );
}
